"""
Invoice endpoints — owner: Bhushan.

REDESIGNED (11 Aug 2026): invoice_id is now REQUIRED in the upload form,
caller-supplied, alphanumeric, and never generated by the backend. Two
concrete new behaviors this brings:

  1. Duplicate detection happens BEFORE running the (slow, costs money)
     extraction pipeline — a resubmitted invoice_id is rejected with 409
     immediately, not discovered after a wasted Groq call.
  2. PUT /invoices/{invoice_id} now exists for deliberately updating an
     existing invoice (e.g. re-processing after a correction), separate
     from POST which only ever creates.

NOTE ON AUTH: still no auth check on these routes — see the original
note left here; Trinkesh's get_current_user dependency still doesn't
exist as of this writing. Unchanged by this redesign.
"""
from __future__ import annotations
from app.auth.dependencies import get_current_user
from app.models import User
import re
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from sqlalchemy.orm import Session, joinedload

from app.database.database import RESOLVED_DATABASE_URL, get_db
from app.database.invoice_repository import (
    InvoiceAlreadyExistsError,
    InvoiceNotFoundError,
    get_firm_id_for_matter,
    insert_invoice_with_line_items,
    invoice_exists,
    update_invoice_with_line_items,
)
from app.models.invoice import Invoice
from app.models.invoice_item import LineItem
# from app.workflows.legal_invoice_platform_agent import run_pipeline

from app.workflow.graph import call_run_invoice_graph
router = APIRouter(prefix="/invoices", tags=["invoices"])

UPLOAD_DIR = Path(__file__).resolve().parent.parent.parent / "uploaded_invoices"
UPLOAD_DIR.mkdir(exist_ok=True)

ALLOWED_EXTENSIONS = {".pdf", ".txt"}  # .txt kept for the same quick-smoke-test path the CLI supports


def _save_upload_to_disk(file: UploadFile, content: bytes) -> Path:
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{suffix}'. Allowed: {sorted(ALLOWED_EXTENSIONS)}",
        )
    if not content:
        raise HTTPException(status_code=400, detail="Uploaded file is empty")

    saved_path = UPLOAD_DIR / f"{uuid.uuid4().hex}_{file.filename}"
    saved_path.write_bytes(content)
    return saved_path


def _normalize_matter_id(matter_id: str) -> str:
    normalized = (matter_id or "").strip()
    if not normalized:
        raise HTTPException(status_code=422, detail="matter_id must be a non-empty alphanumeric string")
    if not re.fullmatch(r"[A-Za-z0-9-]+", normalized):
        raise HTTPException(status_code=422, detail="matter_id must contain only letters, numbers, or hyphens")
    return normalized


@router.post("/submit", status_code=200)

async def submit_invoice(
    matter_id: str = Form(..., description="Required. Alphanumeric matter identifier."),
    file: UploadFile = File(...),
    matter_name: str | None = Form(None, description="Optional human-readable matter name (e.g. 'Nova Retail v. Green Market')."),
    current_user: User = Depends(
        get_current_user
    ),
    # TODO(Trinkesh): once get_current_user exists, add:
    #   current_user = Depends(get_current_user),
):
    """
    Creates a NEW invoice and returns its generated integer invoice_id.

    The client does not supply invoice_id on create; it is generated by
    the database. Duplicate submission is prevented by the unique
    invoice_no + matter_id constraint.
    """
    matter_id = _normalize_matter_id(matter_id)
    content = await file.read()
    saved_path = _save_upload_to_disk(file, content)

    print(f"[submit_invoice] resolved DB url={RESOLVED_DATABASE_URL} matter_id={matter_id} upload_file={file.filename}")
    firm_id = get_firm_id_for_matter(matter_id)
    
    if (
        current_user.firm_id is not None
        and current_user.firm_id != firm_id
):
        raise HTTPException(
            status_code=403,
            detail="Permission denied",
    )
    

    try:
        final_state = call_run_invoice_graph(str(saved_path), matter_id, firm_id, initial_matter_name=matter_name)
    except InvoiceAlreadyExistsError as e:
        raise HTTPException(
            status_code=409,
            detail=str(e),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Pipeline failed: {e}")

    return _build_submit_response(final_state)


@router.put("/{invoice_id}")
async def update_invoice(
    invoice_id: int,
    matter_id: str = Form(..., description="Required. Alphanumeric matter identifier."),
    file: UploadFile = File(...),
    matter_name: str | None = Form(None, description="Optional human-readable matter name to persist with the invoice."),
):
    """
    Updates an EXISTING invoice — re-extracts from a new file and
    replaces the stored fields/line items. invoice_id itself never
    changes; it's the lookup key, taken from the URL path.

    404 if invoice_id doesn't exist — this updates, it doesn't upsert.
    """
    if not invoice_exists(invoice_id):
        raise HTTPException(
            status_code=404,
            detail=f"No invoice with invoice_id={invoice_id!r} — use POST /invoices/submit to create it first.",
        )

    matter_id = _normalize_matter_id(matter_id)
    content = await file.read()
    saved_path = _save_upload_to_disk(file, content)

    firm_id = get_firm_id_for_matter(matter_id)

    # Re-run extraction against the new file, but persist via UPDATE, not
    # a fresh pipeline run through the auto-approve/human-review graph —
    # re-processing an update through the same routing logic as a brand
    # new submission is a bigger design question than this endpoint's
    # scope; for now this does extraction + validation only, then a
    # direct update. Flag at standup if PUT should also re-run the full
    # approval workflow.
    from app.workflows.legal_invoice_platform_agent import (
        extract_text_from_pdf,
        extract_with_groq_call,
    )

    raw_text = extract_text_from_pdf(str(saved_path))
    extracted, confidence_score = extract_with_groq_call(raw_text)
    # Prefer provided matter_name if extraction didn't return one
    if matter_name and not extracted.get("matter_name"):
        extracted["matter_name"] = matter_name

    try:
        update_invoice_with_line_items(
            invoice_id=invoice_id,
            matter_id=matter_id,
            firm_id=firm_id,
            extracted=extracted,
            confidence_score=confidence_score,
            status="pending_review",  # an update always goes back to review, never silently re-auto-approves
        )
    except InvoiceNotFoundError:
        raise HTTPException(status_code=404, detail=f"No invoice with invoice_id={invoice_id!r}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Update failed: {e}")

    updated = get_invoice_or_404(invoice_id)
    return {
        "message": "Invoice updated successfully",
        "invoice": _serialize_invoice(updated),
    }


@router.get("/{invoice_id}")
def get_invoice_endpoint(invoice_id: int, db: Session = Depends(get_db)):
    """
    Look up a persisted invoice + its line items by numeric invoice_id.
    """
    invoice = get_invoice_or_404(invoice_id, db)
    return _serialize_invoice(invoice)


@router.get("")
def list_invoices(db: Session = Depends(get_db)):
    """List all invoices — quick way to eyeball everything submitted so
    far. Useful for a dashboard's landing view later."""
    print(f"[list_invoices] resolved DB url={RESOLVED_DATABASE_URL}")
    invoices = db.query(Invoice).order_by(Invoice.invoice_id).all()
    return [
        {
            "invoice_id": inv.invoice_id,
            "invoice_no": inv.invoice_no,
            "matter_id": inv.matter_id,
            "matter_name": inv.matter_name,
            "firm_id": inv.firm_id,
            "total_amount": inv.total_amount,
            "status": inv.status,
            "confidence_score": inv.confidence_score,
        }
        for inv in invoices
    ]


# --- helpers ---

def get_invoice_or_404(invoice_id: int, db: Session = None) -> Invoice:
    close_after = False
    if db is None:
        from app.database.database import SessionLocal
        db = SessionLocal()
        close_after = True
    try:
        invoice = db.query(Invoice).options(joinedload(Invoice.matter), joinedload(Invoice.line_items)).filter(Invoice.invoice_id == invoice_id).first()
        if not invoice:
            raise HTTPException(status_code=404, detail=f"No invoice with id {invoice_id}")
        return invoice
    finally:
        if close_after:
            db.close()


def _serialize_invoice(invoice: Invoice) -> dict:
    return {
        "invoice_id": invoice.invoice_id,
        "matter_id": invoice.matter_id,
        "matter_name": invoice.matter_name,
        "firm_id": invoice.firm_id,
        "invoice_no": invoice.invoice_no,
        "invoice_date": invoice.invoice_date,
        "billing_period_start": invoice.billing_period_start,
        "billing_period_end": invoice.billing_period_end,
        "total_amount": invoice.total_amount,
        "status": invoice.status,
        "confidence_score": invoice.confidence_score,
        "line_items": [
            {
                "line_item_id": li.line_item_id,
                "line_type": li.line_type,
                "timekeeper": li.timekeeper,
                "role": li.role,
                "hours": li.hours,
                "rate": li.rate,
                "amount": li.amount,
                "description": li.description,
            }
            for li in invoice.line_items
        ],
    }


def _build_submit_response(final_state: dict) -> dict:
    result = {
        "invoice_id": final_state.get("invoice_id"),
        "final_status": final_state.get("final_status"),
        "confidence_score": final_state.get("confidence_score"),
        "extracted": final_state.get("extracted"),
        "is_duplicate": final_state.get("is_duplicate"),
        "validation_passed": final_state.get("validation_passed"),
        "validation_reason": final_state.get("validation_reason"),
        "audit_trail": final_state.get("audit_trail"),
    }
    if final_state.get("is_duplicate"):
        result["warning"] = (
            f"invoice_id {final_state.get('invoice_id')!r} was already flagged as a duplicate "
            f"during processing. It was NOT auto-approved — routed to human review instead."
        )
    return result