"""
Tests for the /invoices HTTP endpoints (app/api/invoices.py).

Client submits matter_id (must reference a real, existing Matter row —
see auth_ctx fixture) and a file; invoice_id is generated by the backend
and returned as a numeric system identifier. Duplicate invoices are
rejected by invoice_no + matter_id.

Updated during the QA pass (14 Aug 2026) to use the auth_ctx fixture
(tests/conftest.py) for a real bearer token and real Matter rows — see
that fixture's docstring for why these were missing before.
"""
import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def client():
    from app.main import app

    return TestClient(app)


class TestHealthCheck:
    def test_health_returns_ok(self, client):
        r = client.get("/health")
        assert r.status_code == 200
        assert r.json() == {"status": "ok"}


class TestSubmitInvoice:
    def test_submit_valid_pdf_returns_200_with_expected_shape(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        body = r.json()
        assert isinstance(body["invoice_id"], int)
        assert body["final_status"] in ("approved", "pending_review")
        assert "extracted" in body
        assert "audit_trail" in body

    def test_submit_accepts_alphanumeric_matter_id(self, client, auth_ctx, sample_native_pdf):
        # matter_id itself is a numeric string (the real Matter PK) —
        # this exercises that a numeric-looking matter_id string works,
        # same as any other valid matter_id would.
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        body = r.json()
        assert isinstance(body["invoice_id"], int)
        assert body["final_status"] in ("approved", "pending_review")

    def test_submit_missing_matter_id_returns_422(self, client, auth_ctx, sample_native_pdf):
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 422

    def test_submit_blank_matter_id_returns_422(self, client, auth_ctx, sample_native_pdf):
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": "   "},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 422

    def test_submit_rejects_unsupported_file_type(self, client, auth_ctx):
        matter_id = auth_ctx["make_matter"]()
        r = client.post(
            "/invoices/submit",
            headers=auth_ctx["headers"],
            data={"matter_id": matter_id},
            files={"file": ("malware.exe", b"not a real file", "application/octet-stream")},
        )
        assert r.status_code == 400

    def test_submit_rejects_empty_file(self, client, auth_ctx):
        matter_id = auth_ctx["make_matter"]()
        r = client.post(
            "/invoices/submit",
            headers=auth_ctx["headers"],
            data={"matter_id": matter_id},
            files={"file": ("empty.pdf", b"", "application/pdf")},
        )
        assert r.status_code == 400

    def test_submit_unknown_matter_id_returns_404(self, client, auth_ctx, sample_native_pdf):
        """QA findings bug #4: a matter_id that doesn't exist yet must be
        a clean 404, not a 500 crash inside the extraction pipeline."""
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": "999999"},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 404

    def test_submit_without_token_returns_401(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code in (401, 403)  # HTTPBearer's own "not authenticated" default is 403


class TestDuplicateSubmission:
    def test_second_submission_of_same_invoice_no_and_matter_returns_409(self, client, auth_ctx, sample_native_pdf):
        """
        Reproduces the reported bug via the actual HTTP endpoint (QA
        findings bug #5). Duplicate detection is based on invoice_no +
        matter_id, and invoice_no is only known after extraction runs —
        see app/api/invoices.py's module docstring.
        """
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            first = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert first.status_code == 200

        with open(sample_native_pdf, "rb") as f:
            second = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert second.status_code == 409
        body = second.json()
        assert "already exists" in body["detail"]
        assert "inv_changes" in body
        assert isinstance(body["inv_changes"], dict)

    def test_duplicate_rejection_does_not_create_a_second_row(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            first = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert first.status_code == 200
        invoice_id = first.json()["invoice_id"]

        with open(sample_native_pdf, "rb") as f:
            second = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert second.status_code == 409

        r = client.get(f"/invoices/{invoice_id}", headers=auth_ctx["headers"])
        assert r.status_code == 200


class TestGetInvoice:
    def test_get_after_submit_returns_matching_data(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            create = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert create.status_code == 200
        invoice_id = create.json()["invoice_id"]

        r = client.get(f"/invoices/{invoice_id}", headers=auth_ctx["headers"])
        assert r.status_code == 200
        body = r.json()
        assert body["invoice_id"] == invoice_id
        assert body["invoice_no"] == "INV-1001"
        assert str(body["matter_id"]) == matter_id

    def test_get_nonexistent_invoice_returns_404(self, client, auth_ctx):
        r = client.get("/invoices/999999", headers=auth_ctx["headers"])
        assert r.status_code == 404


class TestUpdateInvoice:
    def test_put_updates_existing_invoice_same_id(self, client, auth_ctx, sample_native_pdf, sample_scanned_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            create = client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert create.status_code == 200
        invoice_id = create.json()["invoice_id"]

        with open(sample_scanned_pdf, "rb") as f:
            r = client.put(
                f"/invoices/{invoice_id}",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_scanned.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        assert r.json()["invoice"]["invoice_id"] == invoice_id

        listing = client.get("/invoices", headers=auth_ctx["headers"]).json()
        matches = [inv for inv in listing if inv["invoice_id"] == invoice_id]
        assert len(matches) == 1

    def test_put_nonexistent_invoice_returns_404(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            r = client.put(
                "/invoices/999999",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 404


class TestListInvoices:
    def test_list_returns_an_array(self, client, auth_ctx, sample_native_pdf):
        matter_id = auth_ctx["make_matter"]()
        with open(sample_native_pdf, "rb") as f:
            client.post(
                "/invoices/submit",
                headers=auth_ctx["headers"],
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        r = client.get("/invoices", headers=auth_ctx["headers"])
        assert r.status_code == 200
        assert isinstance(r.json(), list)
        assert len(r.json()) >= 1
