"""
Tests for the /invoices HTTP endpoints (app/routers/invoices.py).

REDESIGNED: invoice_id is now generated by the backend database and
returned as a numeric system identifier. Clients submit only matter_id
and the uploaded file. Duplicate invoices are rejected by invoice_no +
matter_id.
"""
import uuid

import pytest
from fastapi.testclient import TestClient


def _unique_matter_id(prefix="M-API"):
    return f"{prefix}-{uuid.uuid4().hex[:8]}"


@pytest.fixture
def client():
    from app.main import app

    return TestClient(app)


class TestHealthCheck:
    def test_health_returns_ok(self, client):
        r = client.get("/health")
        assert r.status_code == 200
        assert r.json() == {"status": "ok"}


class TestSubmitInvoice:
    def test_submit_valid_pdf_returns_200_with_expected_shape(self, client, sample_native_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        body = r.json()
        assert isinstance(body["invoice_id"], int)
        assert body["final_status"] in ("approved", "pending_review")
        assert "extracted" in body
        assert "audit_trail" in body

    def test_submit_accepts_alphanumeric_matter_id(self, client, sample_native_pdf):
        matter_id = _unique_matter_id(prefix="M-ABC")
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        body = r.json()
        assert isinstance(body["invoice_id"], int)
        assert body["final_status"] in ("approved", "pending_review")

    def test_submit_missing_matter_id_returns_422(self, client, sample_native_pdf):
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 422

    def test_submit_blank_matter_id_returns_422(self, client, sample_native_pdf):
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={"matter_id": "   "},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 422

    def test_submit_rejects_unsupported_file_type(self, client):
        r = client.post(
            "/invoices/submit",
            data={"matter_id": _unique_matter_id()},
            files={"file": ("malware.exe", b"not a real file", "application/octet-stream")},
        )
        assert r.status_code == 400

    def test_submit_rejects_empty_file(self, client):
        r = client.post(
            "/invoices/submit",
            data={"matter_id": _unique_matter_id()},
            files={"file": ("empty.pdf", b"", "application/pdf")},
        )
        assert r.status_code == 400

    def test_firm_id_no_longer_required(self, client, sample_native_pdf):
        """firm_id is intentionally NOT a required field anymore — only
        matter_id and the file, per the required upload flow."""
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            r = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200


class TestDuplicateSubmission:
    def test_second_submission_of_same_invoice_no_and_matter_returns_409(self, client, sample_native_pdf):
        """
        Reproduces the reported bug via the actual HTTP endpoint.
        Duplicate detection is now based on invoice_no + matter_id.
        """
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            first = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert first.status_code == 200

        with open(sample_native_pdf, "rb") as f:
            second = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert second.status_code == 409
        assert "already exists" in second.json()["detail"]

    def test_duplicate_rejection_does_not_create_a_second_row(self, client, sample_native_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            first = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert first.status_code == 200
        invoice_id = first.json()["invoice_id"]

        with open(sample_native_pdf, "rb") as f:
            second = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert second.status_code == 409

        r = client.get(f"/invoices/{invoice_id}")
        assert r.status_code == 200


class TestGetInvoice:
    def test_get_after_submit_returns_matching_data(self, client, sample_native_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            create = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert create.status_code == 200
        invoice_id = create.json()["invoice_id"]

        r = client.get(f"/invoices/{invoice_id}")
        assert r.status_code == 200
        body = r.json()
        assert body["invoice_id"] == invoice_id
        assert body["invoice_no"] == "INV-1001"
        assert body["matter_id"] == matter_id

    def test_submit_accepts_alphanumeric_matter_id_for_get(self, client, sample_native_pdf):
        matter_id = _unique_matter_id(prefix="M-XYZ")
        with open(sample_native_pdf, "rb") as f:
            create = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert create.status_code == 200
        invoice_id = create.json()["invoice_id"]

        r = client.get(f"/invoices/{invoice_id}")
        assert r.status_code == 200
        assert r.json()["invoice_id"] == invoice_id
        assert r.json()["matter_id"] == matter_id

    def test_get_nonexistent_invoice_returns_404(self, client):
        r = client.get("/invoices/999999")
        assert r.status_code == 404


class TestUpdateInvoice:
    def test_put_updates_existing_invoice_same_id(self, client, sample_native_pdf, sample_scanned_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            create = client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert create.status_code == 200
        invoice_id = create.json()["invoice_id"]

        with open(sample_scanned_pdf, "rb") as f:
            r = client.put(
                f"/invoices/{invoice_id}",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_scanned.pdf", f, "application/pdf")},
            )
        assert r.status_code == 200
        assert r.json()["invoice_id"] == invoice_id

        listing = client.get("/invoices").json()
        matches = [inv for inv in listing if inv["invoice_id"] == invoice_id]
        assert len(matches) == 1

    def test_put_nonexistent_invoice_returns_404(self, client, sample_native_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            r = client.put(
                "/invoices/999999",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        assert r.status_code == 404


class TestListInvoices:
    def test_list_returns_an_array(self, client, sample_native_pdf):
        matter_id = _unique_matter_id()
        with open(sample_native_pdf, "rb") as f:
            client.post(
                "/invoices/submit",
                data={"matter_id": matter_id},
                files={"file": ("sample_invoice_native.pdf", f, "application/pdf")},
            )
        r = client.get("/invoices")
        assert r.status_code == 200
        assert isinstance(r.json(), list)
        assert len(r.json()) >= 1
