"""
Invoice persistence — owner: Bhushan (ERD: INVOICE, LINE_ITEM entities).

REDESIGNED: invoice_id is now a system-generated integer primary key.
This file's functions reflect that:
  - insert_invoice_with_line_items() does not take invoice_id; the DB
    generates it and returns the integer value.
  - update_invoice_with_line_items() still receives invoice_id as the
    lookup key for updates.
  - invoice_exists()/get_invoice() take the numeric invoice_id.
"""
from __future__ import annotations

from sqlalchemy.exc import IntegrityError

from app.database.database import SessionLocal
from app.models.invoice import Invoice
from app.models.invoice_item import LineItem
from app.models.matter import Matter


class InvoiceAlreadyExistsError(Exception):
    """Raised by insert_invoice_with_line_items() if an invoice with the
    same invoice_no and matter_id already exists.
    Distinct from a generic DB error so the API layer can turn this into
    a clean 409 instead of a 500."""
    def __init__(self, invoice_no: str, matter_id: str):
        self.invoice_no = invoice_no
        self.matter_id = matter_id
        super().__init__(f"Invoice with invoice_no={invoice_no!r} already exists for matter_id={matter_id!r}")


class InvoiceNotFoundError(Exception):
    """Raised by update_invoice_with_line_items() if invoice_id doesn't
    exist yet — PUT here means "update an existing invoice," not upsert."""
    def __init__(self, invoice_id: int):
        self.invoice_id = invoice_id
        super().__init__(f"No invoice with invoice_id={invoice_id!r}")


def invoice_exists(invoice_id: int) -> bool:
    """Lookup by numeric system-generated invoice_id."""
    db = None
    try:
        db = SessionLocal()
        return db.query(Invoice).filter(Invoice.invoice_id == invoice_id).first() is not None
    except Exception as e:
        print(f"[invoice_exists] lookup failed ({e}) — defaulting to False")
        return False
    finally:
        if db is not None:
            db.close()


def invoice_exists_by_business_key(invoice_no: str, matter_id: str) -> bool:
    invoice_no = invoice_no.strip() if isinstance(invoice_no, str) else invoice_no
    matter_id = matter_id.strip() if isinstance(matter_id, str) else matter_id
    db = None
    try:
        db = SessionLocal()
        return db.query(Invoice).filter(
            Invoice.invoice_no == invoice_no,
            Invoice.matter_id == matter_id,
        ).first() is not None
    except Exception as e:
        print(f"[invoice_exists_by_business_key] lookup failed ({e}) — defaulting to False")
        return False
    finally:
        if db is not None:
            db.close()


def get_invoice(invoice_id: int):
    """Fetch a single Invoice row (with line_items loaded) by its
    numeric id, or None."""
    db = SessionLocal()
    try:
        return db.query(Invoice).filter(Invoice.invoice_id == invoice_id).first()
    finally:
        db.close()


def get_firm_id_for_matter(matter_id: str):
    """
    Best-effort lookup: the new upload flow no longer requires the caller
    to pass firm_id directly (only invoice_id + matter_id + file) — a
    matter already belongs to a firm, so derive it instead of asking for
    redundant, potentially-inconsistent data.

    Returns None (not an error) if the matter doesn't exist — Matter is
    currently a Bhushan-added placeholder (see app/models/matter.py) with
    no real seeded data in most dev setups, so this has to degrade
    gracefully rather than block every submission until Rajat's real
    Matter/seed data lands.
    """
    db = SessionLocal()
    try:
        matter = db.query(Matter).filter(Matter.matter_id == matter_id).first()
        return matter.firm_id if matter else None
    except Exception as e:
        print(f"[get_firm_id_for_matter] lookup failed ({e}) — proceeding with firm_id=None")
        return None
    finally:
        db.close()


def _apply_line_items(db, invoice_id: int, line_items_data: list) -> None:
    """Shared by insert and update — adds LineItem rows for an invoice
    that's already been added/flushed to the session."""
    for li in (line_items_data or []):
        db.add(LineItem(
            invoice_id=invoice_id,
            line_type=li.get("line_type") or ("expense" if not li.get("timekeeper") else "fee"),
            timekeeper=li.get("timekeeper"),
            hours=li.get("hours"),
            rate=li.get("rate"),
            amount=li.get("amount", 0.0),
            role=li.get("role"),
            description=li.get("description"),
        ))


def insert_invoice_with_line_items(
    matter_id: str,
    firm_id,
    extracted: dict,
    confidence_score: float,
    status: str,
) -> int:
    """
    Inserts one NEW Invoice row plus its LineItem rows. invoice_id is
    system-generated by the database and returned on success.

    Raises InvoiceAlreadyExistsError if the same invoice_no already
    exists for the given matter_id.
    """
    db = SessionLocal()
    invoice_no = extracted.get("invoice_no") or None
    invoice_no = invoice_no.strip() if isinstance(invoice_no, str) else invoice_no
    matter_id = matter_id.strip() if isinstance(matter_id, str) else matter_id

    if invoice_no and invoice_exists_by_business_key(invoice_no, matter_id):
        db.close()
        raise InvoiceAlreadyExistsError(invoice_no, matter_id)

    try:
        invoice = Invoice(
            matter_id=matter_id,
            firm_id=firm_id,
            invoice_no=invoice_no,
            invoice_date=extracted.get("invoice_date") or None,
            billing_period_start=extracted.get("billing_period_start") or None,
            billing_period_end=extracted.get("billing_period_end") or None,
            matter_name=extracted.get("matter_name") or None,
            total_amount=extracted.get("total_amount", 0.0),
            status=status,
            confidence_score=confidence_score,
        )
        db.add(invoice)
        db.flush()  # generates invoice_id before line items are added

        _apply_line_items(db, invoice.invoice_id, extracted.get("line_items"))

        db.commit()
        return invoice.invoice_id
    except IntegrityError as ie:
        db.rollback()
        if invoice_no and invoice_exists_by_business_key(invoice_no, matter_id):
            raise InvoiceAlreadyExistsError(invoice_no, matter_id)
        raise
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def update_invoice_with_line_items(
    invoice_id: int,
    matter_id: str,
    firm_id,
    extracted: dict,
    confidence_score: float,
    status: str,
) -> int:
    """
    Updates an EXISTING invoice's fields and replaces its line items —
    backs PUT /invoices/{invoice_id}. invoice_id itself never changes
    (it's the lookup key, not a field being updated).

    Raises InvoiceNotFoundError if invoice_id doesn't exist — PUT here
    means "update", not "upsert"; use POST /invoices/submit to create.
    """
    db = SessionLocal()
    try:
        invoice = db.query(Invoice).filter(Invoice.invoice_id == invoice_id).first()
        if invoice is None:
            raise InvoiceNotFoundError(invoice_id)

        invoice.matter_id = matter_id
        invoice.firm_id = firm_id
        invoice.matter_name = extracted.get("matter_name") or invoice.matter_name
        invoice.invoice_no = extracted.get("invoice_no") or invoice.invoice_no
        invoice.invoice_date = extracted.get("invoice_date") or invoice.invoice_date
        invoice.billing_period_start = extracted.get("billing_period_start") or invoice.billing_period_start
        invoice.billing_period_end = extracted.get("billing_period_end") or invoice.billing_period_end
        invoice.total_amount = extracted.get("total_amount", invoice.total_amount)
        invoice.status = status
        invoice.confidence_score = confidence_score

        # Replace line items wholesale rather than trying to diff old vs
        # new — simpler and correct for "re-extracted from a new file"
        # semantics, which is what PUT represents here.
        db.query(LineItem).filter(LineItem.invoice_id == invoice_id).delete()
        _apply_line_items(db, invoice_id, extracted.get("line_items"))

        db.commit()
        return invoice_id
    except InvoiceNotFoundError:
        db.rollback()
        raise
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()